# Generated by Django 4.2.7 on 2023-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prci", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
