# Generated by Django 4.2.7 on 2023-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prci", "0003_rename_is_published_publisher_is_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="is_publisher",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
