# Generated by Django 4.2.7 on 2023-11-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prci", "0004_alter_publisher_is_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="publisher_founding_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
